# 要使用本地数据进行训练，需要结合使用 ScriptArguments 和 DatasetMixtureConfig

# DatasetMixtureConfig 参数(不是 ScriptArguments)  
datasets:  
  - path: json  
    # data_files: /workspace/data/rl2-dpo-datas-from-hf-ultrafeedback_binarized/train_dpo.json  
    data_files: /workspace/trl/_study_logs/datasets/_pro.trl.dpo.data.scripts.dataset_samples.ch.json
    split: train  
  - path: json    
    # data_files: /workspace/data/rl2-dpo-datas-from-hf-ultrafeedback_binarized/val_dpo.json  
    data_files: /workspace/trl/_study_logs/datasets/_pro.trl.dpo.data.scripts.dataset_samples.ch.val.json
    split: train  
  
# ScriptArguments 参数  
dataset_train_split: train      # 指定使用第一个 dataset 作为训练集  
dataset_test_split: train       # 指定使用第二个 dataset 作为评估集  
dataset_streaming: false        # 不使用流式加载  

# 其他训练参数  
model_name_or_path: /workspace/models/qwen2.5-0.5b-instruct


# DPOConfig 参数  
beta: 0.1  
loss_type: sigmoid  
per_device_train_batch_size: 1  
# max_steps: 5000
num_train_epochs: 10
learning_rate: 5e-7  
output_dir: /workspace/output/dpo-local  
no_remove_unused_columns: true
